# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  webappapi:
    image: trailcontainerregistry.azurecr.io/backend:latest
  webapp:
    image: trailcontainerregistry.azurecr.io/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - webappapi