# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  webappapi:
    image: trailcontainerregistry.azurecr.io/backend:latest
  webapp:
    image: trailcontainerregistry.azurecr.io/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - webappapi
      
Device: Emulated Desktop
User agent: (host) Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/86.0.4240.75 Safari/537.36
User agent (network): Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/84.0.4143.7 Safari/537.36 Chrome-Lighthouse
CPU/Memory Power: 948
